version: '3.1'

services:
  nginx:
    build: ./nginx
    ports:
      - 80:80
    depends_on:
      - "web"
    volumes:
      - ./static/:/code/static/
      - ./media/:/code/media/
     
  db:
    image: postgres
    restart: always
    volumes:
      - ./pgdb:/var/lib/postgresql/data
    ports:
      - 5432:5432
    env_file: .env


  web:
    build: .
    volumes:
       - ./media:/code/media
    ports:
       - 8001:8000
    depends_on:
       - "db"
    env_file: .env
  
  celery:
    build: 
       context: .
       dockerfile: celery.dockerfile
    volumes:
       - ./media:/code/media
    command: celery -A MultiKart worker --beat --scheduler django --loglevel=info
    depends_on:
       - "db"
    env_file: .env
     


  
  redisdb:
    image: redis
    ports:
      - 6379:6379