# Generated by Django 3.2.2 on 2023-01-16 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shippingadress',
            old_name='Address',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='shippingadress',
            old_name='City',
            new_name='city',
        ),
        migrations.RenameField(
            model_name='shippingadress',
            old_name='Country',
            new_name='country',
        ),
        migrations.RenameField(
            model_name='shippingadress',
            old_name='Region_State',
            new_name='region_state',
        ),
        migrations.RenameField(
            model_name='shippingadress',
            old_name='Zip_Code',
            new_name='zip_code',
        ),
    ]
