# Generated by Django 3.2.2 on 2022-12-19 16:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_wishlist_wishlistitems'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wishlistitems',
            name='wishproduct',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wishlist', to='orders.wishlist'),
        ),
    ]
