# Generated by Django 3.2.2 on 2023-01-06 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_alter_wishlistitems_wishproduct'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderbasket',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
