# Generated by Django 3.2.2 on 2023-02-02 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_orderbasket_transaction_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='color',
            field=models.CharField(default='M', max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderitem',
            name='size',
            field=models.CharField(default='Red', max_length=10),
            preserve_default=False,
        ),
    ]
