# Generated by Django 3.2.2 on 2022-12-16 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_review_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='slug',
            field=models.SlugField(default='slug', max_length=300),
            preserve_default=False,
        ),
    ]
