# Generated by Django 3.2.2 on 2022-12-16 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_product_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(default='slug', max_length=300),
            preserve_default=False,
        ),
    ]
