# Generated by Django 3.2.2 on 2023-02-02 21:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_propertyvalues_amount_instock'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='propertyvalues',
            name='amount_instock',
        ),
    ]
