# Generated by Django 3.2.2 on 2023-02-02 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_remove_propertyvalues_amount_instock'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertyvalues',
            name='amount_instock',
            field=models.IntegerField(default=10),
            preserve_default=False,
        ),
    ]
