# Generated by Django 3.2.2 on 2023-02-07 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_propertyvalues_amount_instock'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='slug',
            field=models.SlugField(default='slug', max_length=300),
            preserve_default=False,
        ),
    ]
